# Generated by Django 6.0.2 on 2026-03-27 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('visits_used', models.IntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('visits_allowed', models.IntegerField(default=10)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_rate', models.DecimalField(decimal_places=2, help_text='Fixed rate at time of payment', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_bulk_payment', models.BooleanField(default=False)),
                ('job_count', models.IntegerField(default=1, help_text='Number of jobs in this payment')),
                ('job_ids', models.TextField(blank=True, help_text='Comma-separated job IDs')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('upi', 'UPI'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='bank', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('admin_notes', models.TextField(blank=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('upi_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('pending_collection', 'Pending Cash Collection'), ('partial_refunded', 'Partially Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('cash', 'Cash'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('upi_transaction_id', models.CharField(blank=True, max_length=100)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('card_type', models.CharField(blank=True, max_length=20)),
                ('cash_received', models.BooleanField(default=False)),
                ('cash_received_date', models.DateTimeField(blank=True, null=True)),
                ('cash_rejection_date', models.DateTimeField(blank=True, null=True)),
                ('cash_rejection_reason', models.CharField(blank=True, max_length=255)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_request_date', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.servicerequest')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
