# Generated by Django 6.0.2 on 2026-03-27 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('cleaning', 'Cleaning'), ('painting', 'Painting'), ('ac_repair', 'AC Repair'), ('appliance', 'Appliance Repair'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('icon', models.CharField(default='fas fa-tools', max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('one_time', 'One Time Service'), ('before_service', 'Before Service Check'), ('after_service', 'After Service Support'), ('monthly', 'Monthly Plan'), ('yearly', 'Yearly Plan'), ('quarterly', 'Quarterly Plan')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_months', models.IntegerField(default=1, help_text='For monthly/yearly plans')),
                ('visits_included', models.IntegerField(default=1, help_text='Number of visits included')),
                ('emergency_visits', models.IntegerField(default=0, help_text='Emergency visits included')),
                ('features', models.JSONField(default=list, help_text='List of features included')),
                ('popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='services.service')),
            ],
        ),
    ]
