# Generated by Django 6.0.2 on 2026-05-06 14:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='issue_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='issues/'),
        ),
    ]
