# Generated by Django 6.0.2 on 2026-03-27 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('cleaning', 'Cleaning'), ('painting', 'Painting'), ('ac_repair', 'AC Repair')], max_length=50)),
                ('experience', models.IntegerField(default=0)),
                ('skills', models.TextField(blank=True, help_text='List your skills (comma separated)')),
                ('service_area', models.CharField(blank=True, help_text='Cities where you work', max_length=200)),
                ('pincodes', models.CharField(blank=True, help_text='Comma separated pincodes', max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='worker_docs/photo/')),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to='worker_docs/id_proof/')),
                ('address_proof', models.ImageField(blank=True, null=True, upload_to='worker_docs/address_proof/')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='worker_docs/certificates/')),
                ('job_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fixed_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('verified', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('on_leave', 'On Leave'), ('unavailable', 'Unavailable'), ('vacation', 'On Vacation')], default='available', max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('both', 'Both')], default='both', max_length=20)),
                ('max_jobs_per_day', models.IntegerField(default=3, help_text='Maximum jobs per day (set by admin)')),
                ('current_jobs_count', models.IntegerField(default=0)),
                ('jobs_today', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('total_ratings', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('completed_jobs_count', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID for instant payments', max_length=100)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('upi', 'UPI'), ('cash', 'Cash Collection')], default='bank', max_length=20)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_paid_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notif_type', models.CharField(choices=[('job_assigned', 'New Job Assigned'), ('job_updated', 'Job Updated'), ('payment_sent', 'Payment Sent'), ('general', 'General')], default='general', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.servicerequest')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
