# Generated by Django 6.0.2 on 2026-03-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
