# Generated by Django 6.0.2 on 2026-04-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workerprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
